homeassistant:
  # Name of the location where Home Assistant is running
  name: JM Home
  # Location required to calculate the time the sun rises and sets
  latitude: 48.8333
  longitude: 2.4833
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 26
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Paris
  # Customization file
  customize: !include customize.yaml

# Enables the frontend
frontend:

# Enables configuration UI
config:

# Enables variable component
variable:
  old_status_climate_away_mode:
    value: "" 
    restore: true
    attributes:
      name: Old Status Climate Away Mode
  old_status_fan_livingroom:
    value: ""
    restore: true
    attributes:
      name: Old Status Fan LivingRoon 
  old_status_fan_bedroom:
    value: ""
    restore: true
    attributes:
      name: Old Status Fan Bedroom 


updater:
  include_used_components: true

recorder:
  purge_keep_days: 3
  purge_interval: 3
  db_url: !secret mysql_path
  exclude: 
    domains:
#      - automation
      - weblink
    entities:
      - sun.sun # Don't record sun data
      - sensor.last_boot # Comes from 'systemmonitor' sensor platform
      - sensor.date


http:
  # Secrets are defined in the file secrets.yaml
  api_password: !secret http_password
  # Uncomment this if you are using SSL/TLS, running in Docker container, etc.
  # base_url: example.duckdns.org:8123

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:
  exclude:
    domains:
 #     - automation
      - weblink
      - group
      - history_graph

history_graph:
  gr1:
    name: Temperature
    entities:
      - sensor.temperature_158d0002042559
      - sensor.temperature_158d00022d081c
      - climate.thermostat
      - sensor.bedroom_temperature
    hours_to_show: 48 
    refresh: 60

  gr2:
    name: Humidite
    entities:
      - sensor.humidity_158d0002042559
      - sensor.humidity_158d00022d081c
      - sensor.salon_air_purifier_humidity
      - sensor.bedroom_air_purifier_humidity
    hours_to_show: 48
    refresh: 60

  gr3:
    name: Fan motor
    entities:
      - sensor.motor_fan_salon
      - sensor.motor_fan_bedroom
    hours_to_show: 48
    refresh: 60

# View all events in a logbook
logbook:

lirc:

# Enables a map showing the location of tracked devices
#map:

# Track the sun
sun:

# Weather prediction
weather:
  - platform: openweathermap
    api_key: !secret openweathermap_token 
    mode: daily
    forecast: true
    monitored_conditions:
      - weather

sensor: !include devices/sensor.yaml

fan:
  - platform: xiaomi_miio
    host: 192.168.1.133
    token: !secret fan_salon_token 
    name: "Fan Salon"

  - platform: xiaomi_miio
    host: 192.168.1.134
    token: !secret fan_chambre_token
    name: "Fan Chambre"

#  - platform: yr

# Text to speech
tts:
  - platform: google
    language: 'fr'

# Cloud
cloud:

notify:
  - name: notify
    platform: pushbullet
    api_key: !secret pushbullet_api_key

light: !include devices/light.yaml

media_player: !include devices/media_player.yaml

input_boolean:
  away:
    name: Vacances
    initial: off
    icon: mdi:home-lock

  bypass_heater:
    name: ByPass
    initial: off

input_datetime:
  bypass_heater_hour:
    name: Hour for the bypass
    has_date: false
    has_time: true   

netatmo:
  api_key: !secret netatmo_api_key
  secret_key: !secret netatmo_secret_key
  username: !secret netatmo_username
  password: !secret netatmo_password

climate:
  - platform: netatmo

scene:
  - name: media_prelight
    entities:
      light.ruban:
        state: on
        rgb_color: [0, 0, 255]
        brightness: 80
      light.salon:
        state: on
        rgb_color: [140, 72, 239]
        brightness: 80

  - name: media_light_pause
    entities:
      light.ruban:
        state: on
        rgb_color: [0, 0, 255]
        brightness: 80
      light.salon:
        state: on
        rgb_color: [255,186,128]
        brightness: 50

  - name: media_light_off
    entities:
      light.ruban:
        state: off
      light.salon:
        state: on
        rgb_color: [255,186,128]
        brightness: 80 

  - name: media_light_play
    entities:
      light.ruban:
        state: on
        rgb_color: [140, 72, 239]
        brightness: 160
      light.salon:
        state: off
      light.light_couloir:
        state: off

binary_sensor:
  - platform: ping
    host: 192.168.1.141
    count: 4
    scan_interval: 10

xiaomi_aqara:
  discovery_retry: 5
  gateways:
    - key: !secret gateway_aqara_token 

switch:
  - platform: xiaomi_miio
    name: xiaomi_switch
    host: 192.168.1.85
    token: !secret switch_aqara_token 

group: !include groups.yaml
automation: !include_dir_merge_list automations/
script: !include scripts/barre_son.yaml
