- platform: group
  name: Chambre
  entities:
    - light.yeelight_color1_7811dcaa3bd9 
    - light.yeelight_color1_7811dcd9215e 

- platform: group
  name: Salon
  entities:
    - light.yeelight_color1_7c49eb129f02 
    - light.yeelight_color1_7c49eb12bdaa 
    - light.yeelight_color1_7811dca8145c 
    - light.yeelight_color1_7811dc6b8dd2 

- platform: group
  name: Ruban
  entities:
    - light.yeelight_strip1_7811dc66f469 
    - light.yeelight_strip1_34ce0087e107 
