- platform: kodi
  host: 192.168.1.100
  name: Kodi

- platform: cast
  host: 192.168.1.100

- platform: cast
  host: 192.168.1.151

- platform: songpal
  name: HT CT800
  endpoint: http://192.168.1.151:10000/sony/

