- platform: systemmonitor
  resources:
    - type: disk_use_percent
      arg: /
    - type: memory_free
    - type: processor_use

- platform: waqi
  token: !secret waqi_token
  locations:
    - Nogent-sur-Marne


- platform: template
  sensors:
    salon_temperature:
      entity_id: climate.thermostat
      value_template: "{{ states.climate.thermostat.attributes.current_temperature }}"
      friendly_name: "Temperature salon"
      unit_of_measurement: '°C'

    bedroom_temperature:
      entity_id: fna.fan_chambre
      value_template: "{{ states.fan.fan_chambre.attributes.temperature }}"
      friendly_name: "Temperature salon"
      unit_of_measurement: '°C'


    salon_air_purifier_humidity:
      entity_id: fan.xiaomi_miio_device
      value_template: "{{ states.fan.xiaomi_miio_device.attributes.humidity }}"
      friendly_name: "Salon Humidity"
      unit_of_measurement: "%"
      device_class: humidity

    living_room_air_purifier_aqi:
      entity_id: fan.xiaomi_miio_device 
      value_template: "{{ states.fan.xiaomi_miio_device.attributes.aqi }}"
      friendly_name: "Salon AQI"
      unit_of_measurement: AQI
      icon_template: mdi:chart-bubble

    bedroom_air_purifier_humidity:
      entity_id: fan.fan_chambre
      value_template: "{{ states.fan.fan_chambre.attributes.humidity }}"
      friendly_name: "Chambre Humidity"
      unit_of_measurement: "%"
      device_class: humidity

    bedroom_air_purifier_aqi:
      entity_id: fan.fan_chambre
      value_template: "{{ states.fan.fan_chambre.attributes.aqi }}"
      friendly_name: "Chambre AQI"
      unit_of_measurement: AQI
      icon_template: mdi:chart-bubble


    temperature_nogent:
      entity_id: weather.openweathermap
      value_template: "{{ states.weather.openweathermap.attributes.temperature }}"
      friendly_name: "Temperature Nogent"
      unit_of_measurement: '°C'

    motor_fan_salon:
      entity_id: fan.xiaomi_miio_device
      value_template: "{{ states.fan.xiaomi_miio_device.attributes.motor_speed }}"
      friendly_name: "Vitesse Ventilateur Salon"
      unit_of_measurement: 'T/M'
      icon_template: mdi:speedometer

    motor_fan_bedroom:
      entity_id: fan.fan_chambre
      value_template: "{{ states.fan.fan_chambre.attributes.motor_speed }}"
      friendly_name: "Vitesse Ventilateur Chambre"
      unit_of_measurement: 'T/M'
      icon_template: mdi:speedometer

    mode_fan_salon:
      entity_id: fan.xiaomi_miio_device
      value_template: "{{ states.fan.xiaomi_miio_device.attributes.mode }}"
      friendly_name: "Mode Ventilateur Salon"
      icon_template: mdi:tune

    mode_fan_bedroom:
      entity_id: fan.fan_chambre
      value_template: "{{ states.fan.fan_chambre.attributes.mode }}"
      friendly_name: "Mode Ventilateur Chambre"
      icon_template: mdi:tune



    battery_temperature_cuisine:
      entity_id: sensor.temperature_158d0002042559
      value_template: "{{ states.sensor.temperature_158d0002042559.attributes.battery_level }}"
      friendly_name: "Batterie Thermometre Cuisine"
      icon_template: mdi:battery
      unit_of_measurement: "%"

    battery_temperature_sdb:
      entity_id: sensor.temperature_158d00022d081c
      value_template: "{{ states.sensor.temperature_158d00022d081c.attributes.battery_level }}"
      friendly_name: "Batterie Thermometre Salle de bain"
      icon_template: mdi:battery
      unit_of_measurement: "%"


