- alias: "chromecast idle"
  trigger:
    - platform: state
      entity_id: media_player.htct800_f55d54 
      to: 'idle'
  action:
    - service: script.turn_on
      entity_id: script.son_chromecast_idle

- alias: "chromecast not idle"
  trigger:
    - platform: state
      entity_id: media_player.htct800_f55d54
      from: 'idle'
  action:
    - service: script.turn_off
      entity_id: script.son_chromecast_idle

