- alias: "open main door"
  trigger:
    - platform: state
      entity_id: binary_sensor.main_door
      to: "on"
  condition:
    - condition: state
      entity_id: input_boolean.away
      state: "off"

  action:
    - service: light.turn_on
      entity_id: light.light_couloir
      data:
       brightness: 255
    - delay: 2:00
    - service: light.turn_off
      entity_id: light.light_couloir

