- alias: "fan livingroom on"
  initial_state: true
  trigger:
    - platform: time
      at: '12:00:00'
    - platform: time
      at: '13:00:00'
    - platform: time
      at: '14:00:00'
    - platform: time
      at: '15:00:00'
    - platform: time
      at: '16:00:00'
    - platform: time
      at: '17:00:00'

  condition:
    - condition: state
      entity_id: input_boolean.away
      state: "off"

  action:
    - service: fan.set_speed
      data:
        entity_id:
          - fan.xiaomi_miio_device 
        speed: auto

- alias: "fan livingroom off"
  initial_state: true
  trigger:
    - platform: time
      at: '03:00:00'

  action:
    - service: fan.turn_off
      data:
        entity_id:
          - fan.xiaomi_miio_device 


- alias: "fan bedroom on"
  initial_state: true
  trigger:
    - platform: time
      at: '12:30:00'
    - platform: time
      at: '13:30:00'
    - platform: time
      at: '14:30:00'
    - platform: time
      at: '15:30:00'
    - platform: time
      at: '16:30:00'
    - platform: time
      at: '17:30:00'

  condition:
    - condition: state
      entity_id: input_boolean.away
      state: "off"

  action:
    - service: fan.set_speed
      data:
        entity_id:
          - fan.fan_chambre
        speed: auto

- alias: "fani bedroom off"
  initial_state: true
  trigger:
    - platform: time
      at: '02:30:00'

  action:
    - service: fan.turn_off
      data:
        entity_id:
          - fan.fan_chambre


- alias: "fan bedroom is in silent"
  initial_state: true 
  trigger:
    platform: state
    entity_id: sensor.mode_fan_bedroom
    to: silent
  action:
    - service: fan.set_speed
      data:
        entity_id:
          - fan.fan_chambre
        speed: auto

- alias: "fan living is in silent"
  initial_state: true
  trigger:
    platform: state
    entity_id: sensor.mode_fan_salon
    to: silent
  action:
    - service: fan.set_speed
      data:
        entity_id:
          - fan.xiaomi_miio_device
        speed: auto

