- alias: "force heater at time"
  initial_state: true
  trigger:
    platform: template
    value_template: "{{ states('sensor.time') == (states.input_datetime.bypass_heater_hour.attributes.timestamp | int | timestamp_custom('%H:%M', False)) }}"
  condition:
    - condition: state
      entity_id: input_boolean.bypass_heater
      state: "on"

  action:
    - service: climate.set_temperature
      data:
        entity_id: climate.netatmo_salon 
        temperature: 20
    - service: input_boolean.turn_off
      data:
        entity_id: input_boolean.bypass_heater 

- alias: "bypass heater is disabled by hand"
  initial_state: true
  trigger:
    platform: state
    entity_id: input_boolean.bypass_heater 
    to: 'off'
  action:
    service: input_datetime.set_datetime
    entity_id: input_datetime.bypass_heater_hour 
    data:
      time: '00:00:00'
    

