- alias: "remote key up"
  initial_state: true
  trigger:
    - platform: event
      event_type: ir_command_received
      event_data:
        button_name: KEY_UP
  action:
    service: light.turn_on
    entity_id: light.salon
    data_template:
      brightness: '{{states.light.salon.attributes.brightness + 40}}'

- alias: "remote key down"
  initial_state: true
  trigger:
    - platform: event
      event_type: ir_command_received
      event_data:
        button_name: KEY_DOWN
  action:
    service: light.turn_on
    entity_id: light.salon
    data_template:
      brightness: '{{states.light.salon.attributes.brightness - 40}}'


- alias: "remote key 1"
  initial_state: true
  trigger:
    - platform: event
      event_type: ir_command_received
      event_data:
        button_name: KEY_NUMERIC_1
  action:
    service: light.turn_on
    entity_id: light.salon
    data:
      brightness_pct: '25'

- alias: "remote key 2"
  initial_state: true
  trigger:
    - platform: event
      event_type: ir_command_received
      event_data:
        button_name: KEY_NUMERIC_2
  action:
    service: light.turn_on
    entity_id: light.salon
    data:
      brightness_pct: '50'

- alias: "remote key 3"
  initial_state: true
  trigger:
    - platform: event
      event_type: ir_command_received
      event_data:
        button_name: KEY_NUMERIC_3
  action:
    service: light.turn_on
    entity_id: light.salon
    data:
      brightness_pct: '75'

- alias: "remote key 4"
  initial_state: true
  trigger:
    - platform: event
      event_type: ir_command_received
      event_data:
        button_name: KEY_NUMERIC_4
  action:
    service: light.turn_on
    entity_id: light.salon
    data:
      brightness_pct: '100'

- alias: "remote key 5"
  initial_state: true
  trigger:
    - platform: event
      event_type: ir_command_received
      event_data:
        button_name: KEY_NUMERIC_5
  action:
    service: light.toggle
    entity_id: light.ruban

- alias: "remote key 6"
  initial_state: true
  trigger:
    - platform: event
      event_type: ir_command_received
      event_data:
        button_name: KEY_NUMERIC_6
  action:
    service: light.toggle
    entity_id: light.salon

- alias: "remote key record"
  initial_state: true
  trigger:
    - platform: event
      event_type: ir_command_received
      event_data:
        button_name: KEY_RECORD
  action:
    service: script.turn_on
    entity_id: script.son_night
 

- alias: "remote key power games"
  initial_state: true
  trigger:
    - platform: event
      event_type: ir_command_received
      event_data:
        button_name: KEY_GAMES
  action:
    service: script.turn_on
    entity_id: script.son_switch

- alias: "remote key power media"
  initial_state: true
  trigger:
    - platform: event
      event_type: ir_command_received
      event_data:
        button_name: KEY_MEDIA
  action:
    service: script.turn_on
    entity_id: script.son_media

- alias: "remote key volume down"
  initial_state: true
  trigger:
    - platform: event
      event_type: ir_command_received
      event_data:
        button_name: KEY_VOLUMEDOWN
  action:
    service: media_player.volume_set
    entity_id: media_player.ht_ct800
    data_template:
      volume_level: '{{states.media_player.ht_ct800.attributes.volume_level - 0.02 }}'

- alias: "remote key volume up"
  initial_state: true
  trigger:
    - platform: event
      event_type: ir_command_received
      event_data:
        button_name: KEY_VOLUMEUP

  action:
    service: media_player.volume_up
    entity_id: media_player.ht_ct800
    data:
      entity_id: media_player.ht_ct800


- alias: "remote key next song"
  initial_state: true
  trigger:
    - platform: event
      event_type: ir_command_received
      event_data:
        button_name: KEY_NEXTSONG

  action:
    service: media_player.media_next_track
    entity_id: media_player.htct800_f55d54

- alias: "remote key previous song"
  initial_state: true
  trigger:
    - platform: event
      event_type: ir_command_received
      event_data:
        button_name: KEY_PREVIOUSSONG

  action:
    service: media_player.media_previous_track
    entity_id: media_player.htct800_f55d54

- alias: "remote key pause"
  initial_state: true
  trigger:
    - platform: event
      event_type: ir_command_received
      event_data:
        button_name: KEY_PAUSE

  action:
    service: media_player.media_pause
    entity_id: media_player.htct800_f55d54

- alias: "remote key play"
  initial_state: true
  trigger:
    - platform: event
      event_type: ir_command_received
      event_data:
        button_name: KEY_PLAY

  action:
    service: media_player.media_play
    entity_id: media_player.htct800_f55d54


- alias: "remote key mute"
  initial_state: true
  trigger:
    - platform: event
      event_type: ir_command_received
      event_data:
        button_name: KEY_MUTE

  action:
    service: media_player.media_mute
    entity_id: media_player.ht_ct800


- alias: "switch on"
  initial_state: true
  trigger:
    - platform: event
      event_type: ir_command_received
      event_data:
        button_name: KEY_AUDIO
  action:
    service: script.turn_on
    entity_id: script.son_power_on

- alias: "switch off"
  initial_state: true
  trigger:
    - platform: event
      event_type: ir_command_received
      event_data:
        button_name: KEY_EXIT
  action:
    service: script.turn_on
    entity_id: script.son_power_off

